import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

await mkdir('screenshots', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [], externalRequests = [];
const baseURL = process.env.GARDEN_URL || 'http://localhost:5187';
page.on('request', request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(baseURL).origin) externalRequests.push(request.url()); });
page.on('pageerror', e => errors.push(e.message));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await page.goto(baseURL, { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__garden?.ready, null, { timeout: 60000 }).catch(error => { console.error(errors); throw error; });
await page.waitForTimeout(2000);
await page.screenshot({ path: 'screenshots/daylight.png' });
const stats = await page.evaluate(() => ({ fish: window.__garden.fishCount, calls: window.__garden.drawCalls, triangles: window.__garden.triangles }));
assert.equal(stats.fish, 6);
await page.locator('#pause').click();
const time = await page.evaluate(() => window.__garden.time);
await page.waitForTimeout(300);
assert.equal(await page.evaluate(() => window.__garden.time), time, 'Pause stops simulated time');
await page.locator('#feed').click();
assert.equal(await page.evaluate(() => window.__garden.paused), false, 'Feeding resumes the garden');
await page.locator('#night').click();
await page.waitForTimeout(4200);
assert.ok(await page.evaluate(() => window.__garden.night > .95));
await page.screenshot({ path: 'screenshots/blue-hour.png' });
await page.locator('#about-open').click();
assert.ok(await page.locator('#about').evaluate(el => el.open));
await page.keyboard.press('Escape');
assert.equal(await page.locator('#about').evaluate(el => el.open), false);
await page.locator('#sound').click();
assert.equal(await page.locator('#sound').getAttribute('aria-pressed'), 'true');
await page.locator('#sound').click();
const home = await page.evaluate(() => window.__garden.camera.position);
await page.mouse.move(800, 500); await page.mouse.down(); await page.mouse.move(1000, 540, { steps: 12 }); await page.mouse.up();
await page.waitForTimeout(500);
assert.notDeepEqual(await page.evaluate(() => window.__garden.camera.position), home, 'Orbit changes the camera');
await page.locator('#reset').click(); await page.waitForTimeout(1500);
const reset = await page.evaluate(() => window.__garden.camera.position);
assert.ok(Math.abs(reset[0] - 10.4) < .1, 'Reset restores the home camera');
await page.locator('#day').click();await page.waitForTimeout(2200);
const downloadPromise = page.waitForEvent('download');await page.locator('#capture').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'komorebi-daylight.png');
await page.waitForTimeout(3600);
await page.setViewportSize({ width: 390, height: 844 });await page.waitForTimeout(800);
await page.screenshot({ path: 'screenshots/mobile.png' });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No mobile horizontal overflow');
assert.deepEqual(errors, [], 'No browser or shader errors');
assert.deepEqual(externalRequests, [], 'All assets are served locally');
console.log('Garden smoke test passed.', stats);
await browser.close();
